# Generated by Django 3.1.1 on 2020-10-15 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20201015_1344'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClientDetails',
            new_name='ClientDetail',
        ),
    ]
