# Generated by Django 3.1.1 on 2020-10-15 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20201015_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientdetail',
            old_name='finace_details',
            new_name='total_expense',
        ),
        migrations.RenameField(
            model_name='clientdetail',
            old_name='finace_details_currency',
            new_name='total_expense_currency',
        ),
        migrations.RemoveField(
            model_name='client',
            name='biography',
        ),
        migrations.RemoveField(
            model_name='clientdetail',
            name='created_at',
        ),
        migrations.AddField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='clientdetail',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientdetail',
            name='project_description',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='clientdetail',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='client.client'),
        ),
        migrations.AlterField(
            model_name='clientdetail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
