# Generated by Django 3.1.1 on 2020-10-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20201015_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetail',
            name='project_title',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientdetail',
            name='project_description',
            field=models.TextField(blank=True),
        ),
    ]
